config/routes.rb
Rails.application.routes.draw do
  resources :functions
  resources :types
  devise_for :users
  root to: 'pages#home'
  get '/search', to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/function.rb
class Function < ApplicationRecord
  belongs_to :type
  belongs_to :user
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :user
  has_many :functions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :types
  has_many :functions, through: :types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_function, only: %i[ show edit update destroy ]

  # GET /functions or /functions.json
  def index
    # @functions = Function.all
    @functions = policy_scope(Function)

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'functions/list', locals: { functions: @functions }, formats: [:html] }
    end

    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query OR example ILIKE :query"
      @functions = Function.where(sql_query, query: "%#{params[:query]}%")
    else
      @functions = Function.all
    end
  end

  # GET /functions/1 or /functions/1.json
  def show
  end

  # GET /functions/new
  def new
    @function = Function.new
    authorize @function
  end

  # GET /functions/1/edit
  def edit
  end

  # POST /functions or /functions.json
  def create
    @function = Function.new(function_params)
    @function.user = current_user

    respond_to do |format|
      if @function.save
        format.html { redirect_to @function, notice: "Function was successfully created." }
        format.json { render :show, status: :created, location: @function }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functions/1 or /functions/1.json
  def update
    respond_to do |format|
      if @function.update(function_params)
        format.html { redirect_to @function, notice: "Function was successfully updated." }
        format.json { render :show, status: :ok, location: @function }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1 or /functions/1.json
  def destroy
    @function.destroy
    respond_to do |format|
      format.html { redirect_to functions_url, notice: "Function was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_function
      @function = Function.find(params[:id])
      authorize @function
    end

    # Only allow a list of trusted parameters through.
    def function_params
      params.require(:function).permit(:name, :description, :example, :type_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :index ]

  def index
    @functions = policy_scope(Function)
    @types = policy_scope(Type).sort

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'functions/list', locals: { functions: @functions }, formats: [:html] }
    end

    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query OR example ILIKE :query"
      @functions = Function.where(sql_query, query: "%#{params[:query]}%")
    else
      @functions = Function.all
    end

    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @types = Type.where(sql_query, query: "%#{params[:query]}%")
    else
      @types = Type.all
    end
  end

  def home
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query OR example ILIKE :query"
      @functions = Function.where(sql_query, query: "%#{params[:query]}%")
    else
      @functions = Function.all
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    # @types = Type.all
    @types = policy_scope(Type).sort

    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @types = Type.where(sql_query, query: "%#{params[:query]}%")
    else
      @types = Type.all
    end
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
    authorize @type
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)
    @type.user = current_user

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
      authorize @type
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml.erb' %>">
<meta name="theme-color" content="#ffffff">

app/views/functions/_form.html.erb
<%= simple_form_for(@function) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :example %>
    <%= f.association :type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/functions/_list.html.erb
<div>
  <% @functions.sort { |a, b| a.name <=> b.name }.each do |function| %>
    <div>
      <p><big><%= link_to "#{function.name}", function %></big> · <small><%= function.type.name %></small></p>
      <p class="description-text"><%= function.description.truncate(140, separator: ' ') %></p>
      <% if policy(function).edit? %>
        <p><%= link_to 'Edit', edit_function_path(function) %></p>
        <p><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/functions/edit.html.erb
<h1>Editing Function</h1>

<%= render 'form', function: @function %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', functions_path %>

app/views/functions/index.html.erb
<div id="functions-index-page">
  <div class="index-container">
    <% if user_signed_in? %>
      <p><%= link_to 'New Function', new_function_path %></p>
    <% end %>
    <%= render 'list', functions: @functions %>
  </div>
  <br>
  <p id="notice"><%= notice %></p>
</div>

app/views/functions/new.html.erb
<div id="functions-new-page">
  <h1>New Function</h1>

  <%= render 'form', function: @function %>

  <%= link_to 'Back', functions_path %>
</div>

app/views/functions/show.html.erb
<div id="functions-show-page">
  <p id="notice"><%= notice %></p>

  <p>
    <%= link_to "#{@function.type.name}", controller: "types", action: "show", id: @function.type %>
  </p>

  <h3>
    <%= @function.name %>
  </h3>

  <p>
    <%= @function.description %>
  </p>

  <p>
    Example:
    <%= @function.example %>
  </p>

  <% if policy(@function).edit? %>
    <%= link_to 'Edit', edit_function_path(@function) %> |
  <% end %>
  <%= link_to 'Back', functions_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactKit | The Easiest Way to Search the React Docs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'application/favicon' %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="Description" CONTENT="Author: A.N. Author, Illustrator: P. Picture, Category: Books, Price:  £9.24, Length: 784 pages">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preload" href="CircularStd-Black.woff2" as="font" type="font/woff2" crossorigin>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if current_page?("/") %>
      <%= render 'shared/home_navbar' %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home-page">
  <div class="container">
    <h1>React<span class="logo-dark">Kit</span></h1>
    <div class="search-bar">
      <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "search-input",
          placeholder: "Search for classes or methods..."
        %>
        <%= submit_tag "", class: "btn" %>
      <% end %>
    </div>
  </div>
  <div class="footer-text">
    <p>
      <small>See ruby-doc.org for more</small> 🔥
    </p>
  </div>
</div>

app/views/pages/index.html.erb
<div id="pages-index-page">
  <div class="index-container">
    <% if @types.count > 0 %>
    <div class="class-container">
      <h5>Classes</h5>
      <% @types.sort { |a, b| a.name <=> b.name }.each do |type| %>
        <div>
          <p><big><%= link_to "#{type.name}", type %></big> · <small>Class</small></p>
          <p class="description-text"><%= type.description.truncate(140, separator: ' ') %></p>
        </div>
      <% end %>
    </div>
    <% end %>
    <% if @functions.count > 0 %>
      <h5>Methods</h5>
      <%= render 'functions/list', functions: @functions %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_home_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="navbar-home">
  <div>
    <%= link_to 'Classes', types_path %>
    <%= link_to 'Methods', functions_path %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom">
  <div class="navbar-container">
    <div class="row">
      <div class="navbar-left">
        <%= link_to '/' do %>
          <h1>React<span class="logo-dark">Kit</span></h1>
        <% end %>
        <%= render 'shared/search' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="navbar-right">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Action", "#", class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="navbar-bottom">
      <% if current_page?("/search") %>
        <%= link_to 'All', search_path, :class => "active" %>
      <% else %>
        <%= link_to 'All', search_path %>
      <% end %>
      <% if current_page?("/types") %>
        <%= link_to 'Classes', types_path, :class => "active" %>
      <% else %>
        <%= link_to 'Classes', types_path %>
      <% end %>
      <% if current_page?("/functions") %>
        <%= link_to 'Methods', functions_path, :class => "active"  %>
      <% else %>
        <%= link_to 'Methods', functions_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search-bar">
  <% if current_page?(controller: 'devise/sessions', action: 'new') %>
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes or methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% elsif current_page?(controller: 'devise/passwords', action: 'new') %>
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes or methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% elsif current_page?(controller: 'devise/passwords', action: 'edit') %>
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes or methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% elsif current_page?(controller: 'devise/registrations', action: 'cancel') %>
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes or methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% elsif current_page?(controller: 'devise/registrations', action: 'new') %>
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes or methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% elsif current_page?(controller: 'devise/registrations', action: 'edit') %>
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes or methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% elsif current_page?(controller: 'types', action: 'index') %>
    <%= form_tag types_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% elsif current_page?(controller: 'functions', action: 'index') %>
    <%= form_tag functions_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% else %>
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Search for classes or methods..."
      %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  <% end %>
</div>

app/views/types/_form.html.erb
<%= simple_form_for(@type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<div id="types-index-page">
  <div class="index-container">
    <div>
      <% @types.sort { |a, b| a.name <=> b.name }.each do |type| %>
        <div>
          <p><big><%= link_to "#{type.name}", type %></big></p>
          <p><%= type.description.truncate(140, separator: ' ') %></p>
          <% if policy(type).edit? %>
            <p><%= link_to 'Edit', edit_type_path(type) %></p>
            <p><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <br>

  <% if user_signed_in? %>
    <%= link_to 'New Type', new_type_path %>
  <% end %>
  <p id="notice"><%= notice %></p>
</div>

app/views/types/new.html.erb
<div id="types-new-page">
  <h1>New Type</h1>

  <%= render 'form', type: @type %>

  <%= link_to 'Back', types_path %>
</div>

app/views/types/show.html.erb
<div id="types-show-page">
  <p id="notice"><%= notice %></p>

  <h3>
    <%= @type.name %>
  </h3>

  <p>
    <%= @type.description %>
  </p>

  <p>
    <small>Added by: <%= @type.user.email.truncate(20, separator: '@') %></small>
  </p>
  <% if policy(@type).edit? %>
    <%= link_to 'Edit', edit_type_path(@type) %> |
  <% end %>
  <%= link_to 'Back', types_path %>
</div>